name: Github Actions Demo

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git ls-files
      
    
      
      
  
      


